### ISSUE TITLE
3D vectored Code

### ISSUE THREAD

**Issue by WesleyTheGeolien** [mycarta/t21-hack-footprint#1]
Currently the code works on 2D time slices and when applying to a cube we iterate over each time slice one by one.

The objective is to run this code in native 3D

- [x] Pad
- [x] Run FFTs
- [x] Unpad

The padding and un-adding can be extended from the current code.

For the FFT bumpy proposes an fftN version of their fft2. From what I understand this generalizes the FFTs to a N dimensional space.

However fft2 can be applied to a data cube (or N dimensions for that matter) but ONLY works along 2 axes.

Question: Do we need/want an N dimensional implementation or does a 2D ftt along each time slice work fine?

**Comment by mycarta** [comment]
I think we will need to test on a larger volume 2D vs 3D. Cfr #4 

There could be an additional POTENTIAL benefit (this has to be verified) from going to 3D other than speed, that has to do with the automatic designing of the filter using morphology. This has  come up in some of the work that @scibbatical did with a full (proprietary) 3D: when the footprint peaks on the spectrum are not distinct enough to be automatically picked, Elwyn has been successfully applying stacking of spectra form different time slices to improve the performance of the morphology routine (stack up peaks, stack out 'noise' (with quotation marks because really it is the spectral signature of the geologic 'signal' ... one man's trash is another man's treasure 👍  ) .
In subsequent discussions with Elwyn I've suggested moving to 3D FFT we might get two birds with a stone: both better performance, and better peaks, but this is still all theoretic.

**Comment by leocd91** [comment]
Hi guys, 
Sorry, still caught up with some work.
is this still open? I can update the 3D FFT one to the `utils` if it still needed.

**Comment by mycarta** [comment]
I think as agreed in conversation the current implementation is good. We do not need 3D fit with fftn (although @scibbatical might continue to work on stacking but it is clear that that is separate)
Closing it.
